site_name: Pirus Unggul Services
site_description: Pirus Unggul Services is a leading provider of innovative solutions in the field of
site_url: https://example.com

theme:
  logo: about/assets/Logo_KE_transparent.png
  favicon: about/assets/Logo_KE_transparent.png
  # icon:
  #   previous: fontawesome/solid/angle-left
  #   next: fontawesome/solid/angle-right
  name: material
  # theme:
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: cyan
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.path
    - search.suggestions
    - search.highlight
    - search.share
    - content.code.copy
    - content.tooltips

plugins:
  - search
  - tags
  - glightbox

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
      # clickable_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - tables
  - abbr
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      title: On this page

extra:
  generator: false
copyright: Copyright &copy; 2025 - Pirus Unggul Services


nav:
  - Home: index.md
  - About:
      - Overview: about/about.md
      - Team: about/test1.md

  - Tags: tags.md